on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        description: "What type of releease?"
        default: rc
        options:
          - rc
          - stable
          - graduate

permissions:
  id-token: write
  contents: write
  
name: release

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_CONFIG_PROVENANCE: true
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Coverage
        run: pnpm coverage

      - name: Build
        run: pnpm build

      - run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_NAME }}"

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@oqx"

      - name: Release candidate
        run: pnpm release-it --ci --preRelease=rc
        if: ${{ github.event.inputs.releaseType == 'rc' }}

      - name: Stable release
        run: pnpm release-it --ci
        if: ${{ github.event.inputs.releaseType == 'stable'}}

      - name: Graduate release
        run: pnpm release-it --ci patch
        if: ${{ github.event.inputs.releaseType == 'graduate'}}
